### ISSUE TITLE
Readme file outdated about backup

### ISSUE THREAD

**Issue by bayeslearner** [bitnami/bitnami-docker-spark#28]
Instruction about backup does not make sense.  /bitnami/spark:latest doesn't exist.

**Comment by alemorcuq** [comment]
You are right. We will review that. Thanks!

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
