### ISSUE TITLE
Not able to write spark dataframe.

### ISSUE THREAD

**Issue by msinha251** [bitnami/bitnami-docker-spark#30]
**Description**

I have create spark cluster with bitnami helm chart and able to connect with it from jupyter hub (deployed on k8s as seperate deployment). I am able to preprocess the data on spark cluster but unable to save the pyspark dataframe. Getting below error:
_Job aborted due to stage failure: Task 0 in stage 6.0 failed 4 times, most recent failure: Lost task 0.3 in stage 6.0 (TID 15, 10.244.1.17, executor 0): ExitCodeException exitCode=1: chmod: changing permissions of '/opt/bitnami/spark/<**PVC Sharing with spark cluster and jupyter hub**>/output/_temporary/0/_temporary/attempt_20210324111431_0006_m_000000_15': Operation not permitted_

**Steps to reproduce the issue:**

1. Helm install spark bitnami/spark
2. Kubectl apply -f jupyterhub-deployment.yaml
3. Inside jupyter hub add spark conf with jupyterHub container IP
4. Read file from PVC. Do some pyspark stuff _df = spark.read.format('parquet').options(header = "true", inferSchema = "true").load(input_path)_
5. Save df. _df.write.format('parquet').options(header='true').mode("overwrite").save('/opt/bitnami/spark/<**PVC Sharing with spark cluster and jupyter hub**>/output')_

**Describe the results you received:**

Error: 
_Job aborted due to stage failure: Task 0 in stage 6.0 failed 4 times, most recent failure: Lost task 0.3 in stage 6.0 (TID 15, 10.244.1.17, executor 0): ExitCodeException exitCode=1: chmod: changing permissions of '/opt/bitnami/spark/<**PVC Sharing with spark cluster and jupyter hub**>/output/_temporary/0/_temporary/attempt_20210324111431_0006_m_000000_15': Operation not permitted_

**Describe the results you expected:**

Should save files.

**Additional information you deem important (e.g. issue happens only occasionally):**
Using Azure kubernetes service for deploying spark helm chart and jupyterhub deployment with sharing persistent volume claim.

**Comment by alemorcuq** [comment]
Hi, @msinha251.

I think this can be solved allowing the user to deploy custom init containers. Then, the user can define an init container to change the ownership of the folder where the PVC is mounted. Are you interested in contributing with a PR?

**Comment by msinha251** [comment]
Thanks Alejandro for this.
I am running the spark session from jupyter as root user. And also checked the permission of the PVC inside spark containers, it has root permission "drwxrwxrwx 2 root root 0".

Also tried by adding the securityContext for spark bitnami chart and jupyterhub. But issue still persist.

Yeah, sure would love to contribute with PR, but quite new to this. if possible can you please share some steps on this.

Thanks,
Mahesh

**Comment by alemorcuq** [comment]
Maybe a PR is not the best solution for this. This is what I think is happening here:

If you launch the Spark container as root, the processes inside the container won't be running as root but as a daemon user. You can see this here: https://github.com/bitnami/bitnami-docker-spark/blob/adb1089b7c18883dbfd89d867ae3518941f20476/3/debian-10/rootfs/opt/bitnami/scripts/spark/run.sh#L29

From the error you are sharing, it looks like the process is trying to change the mode of a file:

```
ExitCodeException exitCode=1: chmod: changing permissions of '/opt/bitnami/spark/<PVC Sharing with spark cluster and jupyter hub>/output/_temporary/0/temporary/attempt_20210324111431_0006_m_000000_15': Operation not permitted
```

But only the owner of the file or `root` can change its mode. Since the file seems to be owned by root:

```
drwxrwxrwx 2 root root 0
```

And the Spark process is not running as root, the command is failing. 

You can try a security context using the same user to run both Spark and JupyterHub (but not `root` since Spark processes won't run as `root`), and also setting the `fsGroup` to that same user. For example, user `1001`. Give it a try and let me know  how it goes.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
