### ISSUE TITLE
History Server won't load logs since Spark 3

### ISSUE THREAD

**Issue by gqzang** [bitnami/bitnami-docker-spark#31]
**Description**
I am trying to setup history server on Spark3. The history page will show up on port 18080, but when you submit any jobs, nothing will show up on the page, even though the logs was generated in log folder. 

**Steps to reproduce the issue:**

1. In docker-compose.yml file create a master node and several slave nodes, and map home folder to /spark folder on the nodes; Under home directory create ~/events to contain logs.
2. Run docker-compose up command to raise the cluster and make sure it works.
3. log into shell on master node and edit conf/spark-default.yml by adding the following content
    spark.eventLog.enabled true   
    spark.eventLog.dir file:///spark/events
    spark.history.fs.logDirectory file:///spark/events
4. Run $SPARK_HOME/sbin/start-history-server.sh in start history server. Browse to port 18080 to make sure the page loading.
5. Submit test program and check history page

**Describe the results you received:**
No  progress is show in history page.

**Describe the results you expected:**

The test progress should show up when its running as incomplete. 

**Additional information you deem important (e.g. issue happens only occasionally):**
I did the same procedure on several Spark 2 images, and all of them work. It seems that this happens from first version of Spark 3 and to most recent version 3.1.1

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Ubuntu 16 LTS on Intel i7 cpu with 32GB mem

**Comment by alvneiayu** [comment]
hi @gqzang 

Thanks to report the issue. I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks

Álvaro

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
