### ISSUE TITLE
Documentation unclear on how to expose application details in Spark UI

### ISSUE THREAD

**Issue by binarymason** [bitnami/bitnami-docker-spark#35]
First things first -- thanks for all of your work on this project!

Getting things up and running and I would like to inspect the logs or view application details for an exector.  Because everything is in docker the hyperlinks don't work.  I've scoured through the documentation and issues. Unfortunately, it seems unclear on how to fix this.  Any guidance would be appreciated. Happy to contribute to docs if anyone knows a fix.

Thanks!

(screenshot of link that points to internal docker host)
![image](https://user-images.githubusercontent.com/12122953/118145567-b9b83900-b3db-11eb-8e2d-3a8f10202770.png)

**Comment by marcosbc** [comment]
Hi @binarymason, I was able to run the following job:

```bash
$ spark-submit --class org.apache.spark.examples.SparkPi --master spark://127.0.0.1:7077 --deploy-mode cluster file:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.1.1.jar
```

And to access the logs we just need to make sure the hostname is accessible.

Due to the nature of containers, their FQDN will resolve to the temporary hostname that Docker grants them. To avoid that you must either set the `hostname` in your docker-compose to a known value, i.e.:

```yaml
hostname: myhost
```

Or you can force the hostname via this environment variable:

```yaml
- SPARK_PUBLIC_DNS=myhost
```

Unfortunately you would need to manually expose those hostnames in your computer, something Docker does not allow you to do. Due to this, you may considering using the chart instead which makes all URLs available in the cluster: https://github.com/bitnami/charts/tree/master/bitnami/spark
