### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by aramperes** [bitnami/bitnami-docker-spark#40]
Spark 3 supports Java 11. This image should have separate tags for Java 8 and 11.

https://github.com/bitnami/bitnami-docker-spark/blob/45062fed5159dc4892dc5b83e9650b2784d2fccb/3/debian-10/Dockerfile#L12-L16

**Comment by migruiz4** [comment]
Hi @aramperes ,

I'm afraid we're not offering a Spark image with Java 11 right now. 
As a temporary solution, you would need to create a custom image replacing Java 8 with one installing Java 11

Replace this
```Dockerfile
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "1.8.302-0" --checksum 59c0b7440797c7110c76959dbbce5235359b52adf62f99218b2718c04f2d67b6
```
With this
```Dockerfile
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "11.0.12-0" --checksum 14c1274e93b1135d4d1b82ad7985fc2fa7f5d0689b6da18e0c94da37407cd4ea
```

We will take your request into account and evaluate adding support for Spark + Java 8/11

**Comment by aramperes** [comment]
I think this is still valid, it shouldn't be closed. Is this something I'd be able to contribute to?

**Comment by javsalgar** [comment]
Reopening for the time being. The issue is that this use case does not work correctly with our automations, so it will need a substantial amount of work from our engineering team to support this.

**Comment by matthewadams** [comment]
Any update on this?

**Comment by miguelaeh** [comment]
Hi @matthewadams ,
As @javsalgar commented, this is not contemplated by the moment. You can always modify the Dockerfile to install java 11 instead of 8.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
