### ISSUE TITLE
JDBC connection to Apache Spark

### ISSUE THREAD

**Issue by wise-coders** [bitnami/bitnami-docker-spark#41]
I would like to connect to Apache SQL running in the docker image using JDBC. How can I do this? Should I start some JDBC server?
I tried 
```
docker pull bitnami/spark:latest
docker run --name sparksql -p 10000:10000 bitnami/spark:latest
```
And JDBC URL : jdbc:hive2://localhost:10000
But didn't work.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but this image run [start-master.sh](https://github.com/bitnami/bitnami-docker-spark/blob/a1b59ba3eeef80c22d29dee052bcd27667930068/3/debian-10/rootfs/opt/bitnami/scripts/spark/run.sh#L19), and for JDBC you will need to run the `start-thriftserver.sh`.
  I think you could modify the `run.sh` script and build you own image.

**Comment by echosalik** [comment]
I know this might not be what you want, but because searching for JDBC leads to this issue, I am commenting it here.
If you want to connect to a JDBC usl with a driver, you can just bind the file from host to client like this:
```./connectors/mysql-connector-java-8.0.26.jar:/opt/bitnami/spark/jars/mysql-connector-java-8.0.26.jar``` 
either in your `docker-compose` or using `-v`.

Now you can specify the driver in your `Spark Session Configuration` with `spark.driver.extraClassPath`pointing to the location.

As for creating a new image for thriftserver, this works for me:

```Dockerfile
FROM bitnami/spark
USER root
# needed so that thrift server can create the megastore_db directory
RUN chmod g+w /opt/bitnami/spark

CMD ["/bin/bash", "-c","/opt/bitnami/spark/bin/spark-submit --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2"] 
```
This way you do not have to make changes in `run.sh`.

**Comment by rafariossaa** [comment]
Hi,
  @echosalik , thanks for sharing .

**Comment by tfoldi** [comment]
I just pushed #42 to support thriftserver

**Comment by rafariossaa** [comment]
Hi,
  Thanks, It will reviewed and merged.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
