### ISSUE TITLE
Support Spark 3.1.3

### ISSUE THREAD

**Issue by youngnicks** [bitnami/bitnami-docker-spark#86]
### Name and Version

bitnami/spark:3.1.3

### What is the problem this feature will solve?

Provide the ability to use bitnami/spark for jobs using spark 3.1.3.

### What is the feature you are proposing to solve the problem?

The Bitnami Spark image needs to be built for Spark 3.1.3 and a 3.1.3 tag created.

**Comment by youngnicks** [comment]
My team is currently using some 3rd party libraries which are not compatible with Spark 3.2.x keeping us in 3.1.x.

**Comment by carrodher** [comment]
I just created an internal task in order to support the same branches as supported in the upstream project (3.2.x, 3.1.x, and 3.0.x). Since it will require changes in our internal test & release pipeline I can't provide an ETA for this task since it depends on other priorities the team has

**Comment by youngnicks** [comment]
Thank you for creating the task. In the meantime, would it be possible to create & upload spark 3.1.3 tar.gz to stacksmith? I think that is all I'm missing to get my fork working.

**Comment by youngnicks** [comment]
I just noticed that the 3.1.2 spark helm chart is no longer available from your helm repo, chart version 5.7.6. Is there any way to restore that version?

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client.

The `index.yaml` is stored in this repository under the [_index_ branch](https://github.com/bitnami/charts/tree/index/bitnami), users should be able to use any commit in that branch to add a previous version of the `index.yaml`.

- Manually using `helm repo add`
```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
"bitnami-pre-2022" has been added to your repositories
```
- When used as a dependency in _Chart.yaml_:
```diff
  - name: postgresql
    version: 8.1.0
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: postgresql.enabled
```

**Comment by youngnicks** [comment]
Great, thank you very much!
